# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c84433ac875ca14b9b036e42ff21cb038fd93e0239dd789bc14020672e7f51f6146101bc7bac87be0c3868017bfcae70858eb36dee0fb40292fd59246ac3bc8e

test:
  secret_key_base: ce80e034ff588419045cfea3f28b4e55b81be93ac9348668725d16030f6189334ab84d33fe8a67e1c73df4a2b7a9bcb75a7b8b95a4d77ac27275841a546eef75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
